blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime


from django.db import models


class Post(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="Заголовок",
        help_text="введите название поста",
    )
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    context = models.TextField()
    image = models.ImageField(
        upload_to="blog/",
        blank=True,
        null=True,
        help_text="загрузите изображение поста", )
    created_at = models.DateField(default=datetime.now, verbose_name="дата создания поста")
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_counter = models.PositiveIntegerField(default=0, verbose_name='просмотры')

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["title", "created_at", "views_counter"]

    def __str__(self):
        return f"{self.title}"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from pytils.translit import slugify

from blog.models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'context', 'image', 'is_published')
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        if form.is_valid:
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)


class PostListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self, *arg, **kwargs):
        queryset = super().get_queryset(*arg, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'context', 'image', 'is_published')

    def form_valid(self, form):
        if form.is_valid:
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', args=[self.kwargs.get('pk')])


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="mx-auto p-2">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="text-center">
                            <div class="card-body">
                                {% csrf_token %}
                            </div>
                            <h3>Действительно ли хотите удалить пост {{ object.title }}?</h3>
                            <p>Он собрал просмотров: {{ object.views_counter}} </p>
                        </div>
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                        <a href="{% url 'blog:post_list' %}" class="btn btn-warning" role="button">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}


<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}">
                    <div class="card-body">
                        <h2>{{object.title}} {{object.slug}}</h2>
                        <p class="card-text">{{object.context}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:post_list' %}"
                                   role="button">Назад</a>
                                <a class="btn btn-warning" href="{% url 'blog:post_update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'blog:post_delete' object.pk %}"
                                   role="button">Удалить</a>

                            </div>
                            <small class="text-body-secondary">Просмотры: {{ object.views_counter }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    {% if object %}
                    <button type="submit" class="btn btn-warning">
                        Редактировать
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                        Создать
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row mb-4">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'blog:post_create' %}"
               role="button">Создать пост</a>
        </div>
    </div>
</div>

{% for object in object_list %}
<div class="card text-center mb-4">
    <div class="card-header">
        {{ object.created_at }}
    </div>
    <div class="card-body">
        <h2> {{ object.title }}</h2>
        <p class="card-text">{{ object.context|slice:':100' }}...<a href="{% url 'blog:post_detail' object.pk %}">см. далее</a></p>
    </div>
    <div class="card-footer text-body-secondary">
        <div class="btn-group">
            <a href="{% url 'blog:post_detail' object.pk %}" class="btn btn-primary">Перейти</a>
            <a class="btn btn-warning" href="{% url 'blog:post_update' object.pk %}"
               role="button">Редактировать</a>
            <a class="btn btn-danger" href="{% url 'blog:post_delete' object.pk %}"
               role="button">Удалить</a>

        </div>
        Просмотры: {{ object.views_counter}}
    </div>
</div>
{% endfor %}
{% endblock %}