blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),

]

catalog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    VersionCreateView, VersionUpdateView, VersionDeleteView, VersionDetailView, VersionListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/version/create', VersionCreateView.as_view(), name='version_create'),
    path('products/version/update/<int:pk>', VersionUpdateView.as_view(), name='version_update'),
    path('products/version/<int:pk>/delete', VersionDeleteView.as_view(), name='version_delete'),
    path('products/version/<int:pk>/detail', VersionDetailView.as_view(), name='version_detail'),
    path('products/verion/list', VersionListView.as_view(), name='version_list'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from datetime import datetime

from django.db import models

from config import settings


class Category(models.Model):
    '''Создаем модель категории товаров'''
    name = models.CharField(
        max_length=50,
        verbose_name="наименование",
        help_text="введите наименование категории",
    )
    description = models.CharField(
        max_length=200, verbose_name="описание", help_text="введите описание категории"
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    '''Модель продукта'''
    name = models.CharField(
        max_length=50,
        verbose_name="наименование продукта",
        help_text="введите наименование продукта",
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(
        max_length=150, verbose_name="описание", help_text="опишите продукта"
    )
    image = models.ImageField(
        upload_to="products/",
        blank=True,
        null=True,
        help_text="загрузите изображение продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="категория",
        help_text="введите название категории",
        related_name="product",
    )
    price = models.IntegerField(
        verbose_name="стоимость", help_text="стоимость продукта"
    )
    created_at = models.DateField(default=datetime.now, verbose_name="дата создания")
    updated_at = models.DateField(default=datetime.now, verbose_name="дата редактирования")
    views_counter = models.PositiveIntegerField(default=0, verbose_name='просмотры')

    def get_active_version(self):
        return self.versions.filter(is_current=True).first()

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category", "price", "created_at", "updated_at"]
        permissions = [
            ('can_edit_description', 'Can edit description'),
            ('can_edit_category', 'Can edit category'),
            ('set_published', 'Can publish product'),
        ]

    def __str__(self):
        return f"{self.name}"


class Version(models.Model):
    '''Модель версии продукта'''
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="Продукт",
        help_text="Выберите продукт, к которому относится версия",
        related_name="versions"
    )
    version_number = models.SmallIntegerField(
        verbose_name="Номер версии",
        help_text="Введите номер версии"
    )
    version_name = models.CharField(
        max_length=100,
        verbose_name="Название версии",
        help_text="Введите название версии"
    )
    is_current = models.BooleanField(
        default=True,
        verbose_name="Текущая версия",
        help_text="Установите, если это текущая версия продукта"
    )

    def save(self, *args, **kwargs):
        # Если номер версии не установлен, получаем максимальный номер версии для продукта
        if not self.version_number:
            max_version = Version.objects.filter(product=self.product).aggregate(models.Max('version_number'))[
                'version_number__max']
            self.version_number = (max_version + 1) if max_version is not None else 1

        # Устанавливаем флаг is_current для всех предыдущих версий в False
        Version.objects.filter(product=self.product, is_current=True).update(is_current=False)

        # Устанавливаем текущую версию как актуальную
        self.is_current = True

        # Сохраняем версию
        super().save(*args, **kwargs)

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["-is_current", "version_number"]
        constraints = [
            models.UniqueConstraint(fields=['product', 'version_number'], name='unique_product_version')
        ]

    def __str__(self):
        return f"{self.version_name} (Версия {self.version_number})"

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price',)

    def clean_name(self):
        clean_data = self.cleaned_data['name']

        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words:
            if word in clean_data:
                raise forms.ValidationError(
                    'Вы не можете использовать запрещенные слова в названии продукта или описании продукта')
            return clean_data

    def clean_description(self):
        clean_data = self.cleaned_data['description']

        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words:
            if word in clean_data:
                raise forms.ValidationError(
                    'Вы не можете использовать запрещенные слова в названии продукта или описании продукта')
            return clean_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category',)


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version

        fields = ('product', 'version_name',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version
from catalog.services import get_products_from_cache


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for product in context['products']:
            product.active_version = product.get_active_version()
        return context

    def get_queryset(self):
        return get_products_from_cache()


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Привязываем текущего пользователя к продукту
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')


    def get_form_class(self):
        user = self.request.user

        # Здесь выводим все права пользователя в консоль
        print(user.get_all_permissions())  # Это выведет все права пользователя в терминал

        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_edit_description") and user.has_perm(
                "catalog.can_edit_category") and user.has_perm("catalog.set_published"):
            print("Модераторская форма выбрана")  # Добавь этот вывод для проверки
            return ProductModeratorForm
        raise PermissionDenied

        print("Модераторская форма выбрана")  # Добавь этот вывод для проверки


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class VersionListView(ListView):
    model = Version
    context_object_name = 'versions'


class VersionDetailView(DetailView):
    model = Version


class VersionDeleteView(DeleteView):
    model = Version
    success_url = reverse_lazy('catalog:product_list')


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

# class ProductCreateView(CreateView):
#     model = Product
#     fields = ('name', 'description', 'image', 'category', 'price')
#     success_url = reverse_lazy('catalog:product_list')
#


# class ProductUpdateView(UpdateView):
#     model = Product
#     fields = ('name', 'description', 'image', 'category', 'price')
#
#     def get_success_url(self):
#         return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])
#
#     def form_valid(self, form):
#         if form.is_valid:
#             new_post = form.save()
#             new_post.slug = slugify(new_post.name)
#             new_post.save()
#
#         return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Dvyatochka</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html'%}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Магазин продуктов</h1>
                <p class="lead text-body-secondary">Сайт находится на этапе тестирования.<br> С каждым новым обновлением
                    у вас появляется больше возможностей купить продкуты.</p>
                <p>
                <div class="btn-group">
                    <a href="{% url 'catalog:product_create'%}" class="btn btn-primary my-2">Создать продукт</a>

                    <a href="{% url 'catalog:product_list'%}" class="btn btn-primary my-2">Все продукты</a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'catalog:version_create'%}" class="btn btn-primary my-2">Создать версию</a>
                    <a href="{% url 'catalog:version_list'%}" class="btn btn-primary my-2">Посмотреть версии</a>
                </div>
                <a href="{% url 'blog:post_list'%}" class="btn btn-primary my-2">Наш блог</a>
                </p>
            </div>
        </div>
    </section>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="mx-auto p-2" >
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="text-center">
                            <div class="card-body">
                                {% csrf_token %}
                            </div>
                            <h3>Действительно ли хотите удалить {{ object.name }}?
                        </div>
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning" role="button">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6 mb-4">
            <img src="{{ object.image | media_filter }}" class="img-fluid rounded" alt="{{ object.name }}">
        </div>
        <div class="col-md-6">
            <h5 class="text-start">{{ object.name }}</h5>
            <p class="text-muted">{{ object.description_full }}</p>
            <h5 class="text-success">{{ object.price }} ₽</h5>
            <div class="d-flex justify-content-start mt-4">
                <a href="#" class="btn btn-primary me-2">В корзину</a>
                <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-warning me-2">Редактировать</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
            <small class="text-body-secondary mt-3">Просмотров: {{ object.views_counter }}</small>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    {% if object %}
                    <button type="submit" class="btn btn-warning">
                        Редактировать
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                        Создать
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form_main.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    {% if object %}
                    <button type="submit" class="btn btn-warning">
                        Редактировать
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                        Создать
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
            {% for object in object_list %}
            <div class="col">
                <div class="card h-100 shadow-sm">
                    <img src="{{ object.image | media_filter }}" class="bd-placeholder-img card-img-top" alt="{{ object.name }}" style="height: 200px; width: 100%; object-fit: contain; background-color: white;">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name }}</h5>
                        <p class="card-text">{{ object.description }}</p>
                    </div>
                    <div class="card-footer bg-transparent border-0">
                        <div class="d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="{% url 'catalog:product_detail' object.pk %}" role="button">Посмотреть</a>
                            <div class="text-end">
                                <small class="text-muted">Просмотры: {{ object.views_counter }}</small><br>
                                {% if object.get_active_version %}
                                    <small>Активная версия: {{ object.get_active_version.version_name }} (Версия {{ object.get_active_version.version_number }})</small>
                                {% else %}
                                    <small class="text-danger">Активная версия отсутствует.</small>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/version_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="mx-auto p-2">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="text-center">
                            <div class="card-body">
                                {% csrf_token %}
                            </div>
                            <h3>Действительно ли хотите удалить {{ object.version_name }} {{ object.version_number }}?
                        </div>
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning" role="button">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/version_detail.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}">
                    <div class="card-body">
                        <h2>{{object.name}}</h2>
                        <p class="card-text">{{object.description}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}"
                                   role="button">Назад</a>
                                <a class="btn btn-warning" href="{% url 'catalog:product_update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'catalog:product_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                            <small class="text-body-secondary">Просмотры: {{ object.views_counter }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="col-12">
    <form method="post" class="row" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2>Добавить версию</h2>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success"> Сохранить</button>

                        <div class="card-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row mb-4">
    <div class="col-md-12">
        <div class="h-100 p-5 bg-body-tertiary rounded-3">
            <h2>Управление пользователями</h2>
            <p>Здесь вы можете добавлять, редактировать и удалять данные пользователей для рассылок.</p>
            <a href="" class="btn btn-primary" type="button">Добавить пользователя</a>

            <table class="table mt-4">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Email</th>
                    <th scope="col">Дата добавления</th>
                    <th scope="col">Действия</th>
                </tr>
                </thead>
                <tbody>
                <!-- Пример записи, которую можно заменить данными из базы -->
                <tr>
                    {% for version in versions %}
                    <td>{{ version.product }}</td>
                    <td>{{ version.version_name }}</td>
                    <td>{{ version.version_number }}</td>
                    <td>
                        <div class="table-actions">
                            <a class="btn btn-outline-secondary btn-sm" href="{% url 'catalog:version_update' version.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-outline-danger btn-sm" href="{% url 'catalog:version_delete' version.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </td>

                </tr>
                {% endfor %}

                <!-- Пример записи конец -->
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}